"""empty message

Revision ID: f32a1b5a5490
Revises: 4612e4231956
Create Date: 2023-02-27 03:38:26.963415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32a1b5a5490'
down_revision = '4612e4231956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('S3_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('TEST_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_drivers_id'), 'truck_drivers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_drivers_id'), table_name='truck_drivers')
    op.drop_table('truck_drivers')
    # ### end Alembic commands ###
