"""empty message

Revision ID: f3be40b95742
Revises: 
Create Date: 2023-02-27 03:30:20.749876

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import json
import os


# revision identifiers, used by Alembic.
revision = 'f3be40b95742'
down_revision = None
branch_labels = None
depends_on = None


# revision identifiers, used by Alembic.
revision = 'c45aaffb8126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('S3_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    with open(os.path.join(os.path.dirname(__file__), "../bulkDataUpload/users.json")) as f:
        user_data = f.read()
    
    op.bulk_insert(users, json.loads(user_data)) # inserting data in bulk to users table
    
    
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_table('truck_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('S3_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('TEST_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_driver_id'), 'truck_driver', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_driver_id'), table_name='truck_driver')
    op.drop_table('truck_driver')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
